export interface SurgeryReference {
  name: string;
  severity: 'Menor' | 'Intermedia' | 'Mayor' | 'Compleja';
  bleedingRisk: 'Bajo' | 'Moderado' | 'Alto';
  description?: string;
}

export const SURGERY_DATABASE: SurgeryReference[] = [
  { name: 'Apendicectomía (Laparoscópica)', severity: 'Intermedia', bleedingRisk: 'Bajo' },
  { name: 'Colecistectomía (Laparoscópica)', severity: 'Intermedia', bleedingRisk: 'Bajo' },
  { name: 'Hernioplastia Inguinal', severity: 'Intermedia', bleedingRisk: 'Bajo' },
  { name: 'Histerectomía Abdominal', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Reemplazo Total de Cadera', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Reemplazo Total de Rodilla', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Craneotomía (Tumor)', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Bypass Coronario (CABG)', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Resección Intestinal (Colectomía)', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Prostatectomía Radical', severity: 'Mayor', bleedingRisk: 'Alto' },
  { name: 'Tiroidectomía', severity: 'Intermedia', bleedingRisk: 'Bajo' },
  { name: 'Amigdalectomía', severity: 'Intermedia', bleedingRisk: 'Bajo' },
  { name: 'Biopsia de Mama', severity: 'Menor', bleedingRisk: 'Bajo' },
  { name: 'Cirugía de Cataratas', severity: 'Menor', bleedingRisk: 'Bajo' },
  { name: 'Artroscopia de Rodilla', severity: 'Intermedia', bleedingRisk: 'Bajo' },
  { name: 'Laminectomía', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Toracotomía', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Esofagectomía', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Gastrectomía Total', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Nefrectomía', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Cistectomía Radical', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Cirugía de Columna (Multinivel)', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Septoplastia', severity: 'Intermedia', bleedingRisk: 'Bajo' },
  { name: 'Cirugía de Párpados (Blefaroplastia)', severity: 'Menor', bleedingRisk: 'Bajo' },
  { name: 'Liposucción (> 5L)', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Abdominoplastia', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Mastopexia', severity: 'Mayor', bleedingRisk: 'Bajo' },
  { name: 'Cirugía de Varices', severity: 'Intermedia', bleedingRisk: 'Bajo' },
  { name: 'Fistulectomía Anal', severity: 'Menor', bleedingRisk: 'Bajo' },
  { name: 'Hemorroidectomía', severity: 'Intermedia', bleedingRisk: 'Bajo' },
  { name: 'Artrodesis de Columna (1-2 niveles)', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Artrodesis de Columna (> 2 niveles)', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Cirugía de Fontan', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Trasplante Renal', severity: 'Compleja', bleedingRisk: 'Moderado' },
  { name: 'Trasplante Hepático', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Resección de Pulmón (Lobectomía)', severity: 'Compleja', bleedingRisk: 'Moderado' },
  { name: 'Neumonectomía', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Cirugía de Bentall', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Reparación de Aneurisma Aórtico (Abierto)', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Reparación de Aneurisma Aórtico (EVAR)', severity: 'Mayor', bleedingRisk: 'Bajo' },
  { name: 'Endarterectomía Carotídea', severity: 'Mayor', bleedingRisk: 'Bajo' },
  { name: 'Bypass Fémoro-Poplíteo', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Amputación Supracondílea', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Cirugía de Whipple', severity: 'Compleja', bleedingRisk: 'Alto' },
  { name: 'Pancreatectomía Distal', severity: 'Compleja', bleedingRisk: 'Moderado' },
  { name: 'Esplenectomía', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Cirugía Bariátrica (Bypass Gástrico)', severity: 'Mayor', bleedingRisk: 'Bajo' },
  { name: 'Cirugía Bariátrica (Manga Gástrica)', severity: 'Mayor', bleedingRisk: 'Bajo' },
  { name: 'Reducción de Fractura de Fémur', severity: 'Mayor', bleedingRisk: 'Moderado' },
  { name: 'Osteosíntesis de Radio/Cúbito', severity: 'Intermedia', bleedingRisk: 'Bajo' },
  { name: 'Cirugía de Túnel Carpiano', severity: 'Menor', bleedingRisk: 'Bajo' },
  { name: 'Drenaje de Absceso', severity: 'Menor', bleedingRisk: 'Bajo' },
  { name: 'Desbridamiento de Herida', severity: 'Intermedia', bleedingRisk: 'Bajo' },
];
